version: "3.9"
services:
  web: 
    build: 
      context: ./EventsApp.Frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api

  api:
    build: 
      context: ./EventsApp.Backend/
      dockerfile: Dockerfile
    
    environment:
      - NEXTAUTH_SECRET=5167d98083acf31642a428bac4a83f49
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - 5000:80
